language: go

# Be explicit about not needing sudo, so that Travis will use container-based
# infrastructure for our jobs, always, fewer heuristics.
sudo: false

matrix:
  fast_finish: true
  include:
    - go: 1.10.x
      env: UPLOAD_COVERAGE=true
    - go: 1.9.x

branches:
  except:
    - /^(?:exp|wip)(?:[/_-].*)?$/

go_import_path: go.pennock.tech/hmetrics

install:
  - git --version; go version
  - go get -t -v -u ./...
  - test "${UPLOAD_COVERAGE:-false}" != "true" || go get github.com/mattn/goveralls
  - golint || go get -u golang.org/x/lint/golint

script:
  - go vet ./...
  - golint ./...
  - go test -v ./...

after_script:
  - test "${UPLOAD_COVERAGE:-false}" != "true" || goveralls -service=travis-ci -flags=-tags=integration

# pubkey="$(curl -fSs "https://api.travis-ci.org/repos/PennockTech/hmetrics/key" | jq -r .key)"
# openssl rsautl -pubin -inkey <(echo "$pubkey") -encrypt -pkcs <<<"foo" | openssl enc -base64 -A ; echo
#
# In this case, replace "foo" with "<account>:<token>#<channel>"
notifications:
  slack:
    on_success: always
    rooms:
      - secure: "IYl3pd10SmFs3NrVCn0iOlYc+kg7cEUvtR4vD03NNiMLHZgOliro57dM36IMCqTWtl2fgZ2iU9sz1VNr3wcREkdAHhK06058cTNwRRw8nca1ewmLVMzm68PQfmq2DkEgQq08RCMPsT0K8jw3cRV+Bmu5x05q3y6LTyXKNL/xP8iIL//N4NRfvvNSah51vK8CURyhAxEHxPhoeNJ+3zh5FTR1G7flHxtIWk2YfmIUKnAvGOKfRGyH3moDM3+SJspUUlytzsS92tGTvEvIG5INCs8lGir/7EBouMU3DVtd0R2Hl249KDklTHjc0GckadnZ3kelmvrBJ0ll7l0l6TBKwO+Wk2r/OPdkcrX1WMlPO7AwDQ+4y/78oGVeBjUst5RGAvtuyREebi2URAFIcuDR/w/FHecyJgF51Mrt/ez/UOqpd0a8tcH+s9EB58l1TfstcZJNWQ4DtVROwUM6/VFhcMdNUQrRsFUqtpavs+tbR51Embfq2zQvJO5VTS9ccxOK37auCYihlkqb+O6GvhYRH0W14kKwpQ5QabLvKcSMNW9JgDGKE7BxHqLT15fmcqWRaDGM2GMOc/v502KHqU3a2UY8ZDyLX7o4jlzcGu5iAd7GyHA+ZjtBVDkMyIXJVoS/lVpyz2PvlTIc9MMT/KkCcM4WYRidncUXIhpZL3P+Jao="
